name: my first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: list files and read file
              # This step lists files in the current directory and reads the README.md file
              run: |
                echo "Welcome to my first workflow!"
                ls -ltra
                cat README.md
            - name: generate ASCII artwork
              # This step generates ASCII artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt