name: my first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: welcome message
              run: echo "Welcome to my first workflow!"

            - name: List files
              run: ls -l

            - name: Read a file
              run: cat README.md
