name: My First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display welcome message
        run: echo "Hello from my first GitHub Actions workflow!"