name: Generate ASCII Artwork
on: push

jobs:
  generate-ascii:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install cowsay program
        run: sudo apt-get install -y cowsay

      - name: Execute cowsay
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt


      - name: test cowsay CMD
        run: grep -i "dragon" dragon.txt

      - name: Read the file
        run: cat dragon.txt

      - name: checkout the repo files
        run: ls -ltra